### ISSUE TITLE
Unable to build.

### ISSUE THREAD

**Issue by TheEvilness** [AdmiralCurtiss/HyoutaTools#10]
Extracting the master folder, and trying to build either the CLI or GUI versions fails, with GUI giving this:
![image](https://user-images.githubusercontent.com/15717777/75594473-28d09880-5a89-11ea-992d-9eb644b5464c.png)
What exactly am I missing?

**Comment by AdmiralCurtiss** [comment]
You probably haven't cloned the submodules. Try `git submodule update --init --recursive`.

**Comment by TheEvilness** [comment]
Where exactly do I do this? I'm not very used to github and etc..

**Comment by AdmiralCurtiss** [comment]
How did you clone this, did you just download the ZIP? If so you also need to download these two repositories and unpack them into the respective subfolders:
https://github.com/AdmiralCurtiss/HyoutaUtils
https://github.com/AdmiralCurtiss/utf_tab-sharp

Alternatively, you can try cloning with Github Desktop, which I believe clones recursively by default: https://help.github.com/en/desktop/contributing-to-projects/cloning-a-repository-from-github-to-github-desktop

**Comment by TheEvilness** [comment]
Well, I got it to work with Github Desktop, but how do I actually use this tool..?
I haven't found any explanation anywhere..

**Comment by EmirioBomb** [comment]
HyoutaTools is a collection of functions to pack and unpack video game archives.
Although, I used HyoutaTools long time ago, and now changed a lot, but the basic usage maybe the same.
here are some tips may help you:
1. open the folder that HyoutaTools.exe  located.
2. check all files whether satisfied the requirements(*.dll or some new files required)
3. open terminal or command line prompt, type HyoutaTools.exe
4. It will list all of functions
5. check the functions' usage
6. enjoy!
I hope this will help you!
Thanks for all the best works of Admiral

**Comment by TheEvilness** [comment]
Looks incredibly odd to me.. it also has issues loading plugins if I try to run HyoutaToolsCLI from cmd, resulting in gust not getting any commands..

**Comment by AdmiralCurtiss** [comment]
You want to first run `HyoutaToolsCLI` just like that to get a list of tools, then select one by copying the name of one of them and attaching it to the program call, eg. running `HyoutaToolsCLI Gust.g1t.Extract` if you want to run the g1t extractor. Then you usually get the tool-specific usage, in this case:

~~~
>HyoutaToolsCLI Gust.g1t.Extract
Usage: infile.g1t
~~~

So you just attach your g1t filename you want to extract to that, eg.

~~~
>HyoutaToolsCLI Gust.g1t.Extract c:\_nosurge\PS3_GAME\USRDIR\Data\PS3\ui\townmap_ferion.g1t
~~~

or whatever, and then it'll extract that g1t file.

It not loading plugins is normal, it's just notifying you that since there's no `HyoutaToolsPlugins` folder it won't even attempt to load them. I should probably document that infrastructure at some point...

**Comment by TheEvilness** [comment]
Thanks to that explanation, I finally managed to make it work out, thanks for that!
Funny how it was the same game as well, it really is interesting to see how they've designed the UI, etc.
